"use client";

import { Bell } from "lucide-react";
import { useTranslations } from "next-intl";
import { ProjectType } from "@/modules/projects/types/projects";
import { ProjectPermissions } from "@/modules/projects/hooks/permissions/use-project-permissions";
import RemindersList from "@/modules/reminders/components/reminders-list";
import ReminderCreateDialog from "@/modules/reminders/components/reminder-create-dialog";
import { PageHeaderStrip } from "@/modules/projects/components/shared/page-header-strip";

interface ProjectRemindersTabProps {
  project: ProjectType;
  permissions: ProjectPermissions;
}

export function ProjectRemindersTab({
  project,
  permissions,
}: ProjectRemindersTabProps) {
  const t = useTranslations("modules.projects.project.details");

  return (
    <div className="space-y-4">
      <PageHeaderStrip
        icon={Bell}
        title={t("reminders.title", { defaultValue: "Project reminders" })}
        description={t("reminders.description", {
          defaultValue:
            "Schedule reminders linked to this project, sprints, milestones, or specific tasks. Auto-reminders generated by the system also appear here.",
        })}
        actions={
          permissions.canCreateReminder ? (
            <ReminderCreateDialog
              projectId={project.id}
              triggerLabel={t("reminders.create", {
                defaultValue: "Create reminder",
              })}
            />
          ) : null
        }
      />

      <RemindersList
        projectId={project.id}
      />
    </div>
  );
}

export default ProjectRemindersTab;
